import type { Metadata } from "next";
import { Footer, Navbar } from "~/components";
import {
  SettingProvider,
  UserProvider,
  CartProvider,
  NotificationPromise,
} from "~/context";

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <SettingProvider>
        <CartProvider>
          <NotificationPromise>
            <Navbar />
            <main className="w-full min-h-screen">{children}</main>
            <Footer />
          </NotificationPromise>
        </CartProvider>
      </SettingProvider>
    </UserProvider>
  );
}

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    openGraph: {
      type: "website",
      title: "title",
      description: "description",
      siteName: "PWA",
      url: "",
      images: "",
    },
    twitter: {
      card: "summary",
      title: "title",
      description: "description",
      images: "",
      creator: "creator",
    },
  };
}
